### ISSUE TITLE
Plugins for most IDE/editor 

### ISSUE THREAD

**Issue by codad5** [aosasona/Quiksnip#2]
This is not an issue but it would be nice if this software had a plugin for major code editors like vs code / neovim / and JetBrains IDE which can make someone easily highlight a block of code and add it to Quicksnip and  also easily import that same block of code from quick snip, if there is a documentation for the API I might (maybe) try to hop into a vs-code extension (if chanced)

**Comment by aosasona** [comment]
Great idea, but there is no API, this was only updated because I moved the deployment, it's not an active project anymore, neither was it ever completed nor polished. I would not recommend anyone use this anymore either, but it appears very few people still do, that's why I bothered migrating it when I turned off my old server.

**Comment by codad5** [comment]
Ok , I thought it was still active but anyway, really nice project by the way

**Comment by aosasona** [comment]
> Ok , I thought it was still active but anyway, really nice project by the way

Nope, I think it was horrible. It is partly why I scrapped my PHP-Router library, used it in this real project and realized it was an awful approach to building in PHP, although I agree this approach also has its benefits.

**Comment by aosasona** [comment]
https://github.com/aosasona/Quiksnip/issues/1#issue-1595050835

FWIW, I do intend to rewrite it in the future, that is why I did not archive this repo yet, but so far, I haven't had the time to do that and contrary to what I intended in the linked issue, it will most likely all be in PHP anyway using my Phlo library and AlpineJS (+ Torchlight; https://torchlight.dev/).

When that does happen, there will be an API to work with and I will notify you, the idea is nice.
